# Generated by Django 4.1.5 on 2023-01-08 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caption',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='captions', to='api.movie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='movie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='api.movie'),
            preserve_default=False,
        ),
    ]
